### ISSUE TITLE
UI cleanup

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-remediations-frontend#39]
* [x] loading screen for the details page - [PR #41  @ryelo]
* [x] fix breadcrumbs (Remediations > Name) instead of Home > Name [PR #42 @ryelo]
* [x] hide not-implemented stuff in prod [ RedHatInsights/insights-remediations-frontend/pull/53 @jharting ]
* [x] link to app issues [RedHatInsights/insights-remediations-frontend/pull/55 @jharting ]
* [x] link to systems (inventory) [PR #48 @ryelo]
* [x] notification - add link to created/updated remediation [https://github.com/RedHatInsights/insights-frontend-components/pull/254 @jharting ]
* [x] empty remediation table handling - add a paragraph explaining that one can start the process in apps - [PR #45 - @ryelo]
* [x] batch deletion of remediations [PR #44 @jharting ]

**Comment by jharting** [comment]
* [ ] rename Remediation --> Playbook in certain places

**Comment by jharting** [comment]
* [ ] existing or new step
  * the select should have min-width
  * the select perhaps should not be disabled?
* [ ] SelectableTable - when records are removed remove selection

**Comment by ryelo** [comment]
@jharting 

wrt the "existing or new step"

The select is set to auto now, which should take the largest value and set the width to that. Is that not what should happen?

I think the select should be disabled. If it wasn't disabled, then a user might select an existing playbook, but still have "new playbook" selected, creating an Unnamed Playbook

**Comment by jharting** [comment]
@ryelo ok that sounds good
wrt min-width this is what I am observing:
![screenshot_20190201_080236](https://user-images.githubusercontent.com/167352/52107741-d740aa80-25f7-11e9-84e7-52e969bfaa68.png)

**Comment by ryelo** [comment]
@jharting that makes sense. That's weird that it the arrow should be that close to the wording. That's more of a PF bug, I'll put up a PR for it for Insights to fix the problem.
