### ISSUE TITLE
MVP Checklist

### ISSUE THREAD

**Issue by jharting** [RedHatInsights/insights-remediations-frontend#59]
* [x] prod 503 PATCH errors
* [x] sorting + table fixes [RedHatInsights/insights-remediations-frontend/pull/51]
* [x] fetch - use same-origin credentials [RedHatInsights/insights-remediations-frontend/pull/60]
